Daemon mode route reader
haven-life/amorphic-server pull request #23
Opened 2018-10-30 21:20 UTC by nsaenz7

Allow reading of routes from within a dedicated file in application.

How to use:
- create a folder called *server* within your app. place into it an exported function called *routerSetup* in a file called *Routes.js*.
e.g.
your-project > `apps` > application-name-here > `server` > `Routes.js`.
- Define endpoints like usual.
- test your endpoints, making sure to use namespace *api*. e.g. `https://your-website.com/api/your-root-level-custom-endpoint-here`.

2018-10-31 17:56 UTC, sshankar19 requested changes

2018-10-31 17:56 UTC, sshankar19 commented on lib/startUpServer.js
> +
does this need to be a call?

2018-10-31 17:56 UTC, sshankar19 commented on lib/setupCustomRoutes.js
> +
why is the folder called 'server'? Should just be called routes?

Also we should consider naming the file index.js

2018-10-31 17:56 UTC, sshankar19 commented on lib/setupCustomRoutes.js
> +            return routers.routerSetup.call(null, router);
can't we just call all the functions exported in the routers file? no matter what gets exported in that file, we don't have to stick with the convention for function names at least

2018-10-31 19:43 UTC, nsaenz7 commented on lib/startUpServer.js
> +
nope! will change

2018-10-31 21:00 UTC, sshankar19 commented
Can you point this to the swat/feature/daemon-mode branch we talked about today?

2018-11-01 14:38 UTC, nsaenz7 commented on lib/setupCustomRoutes.js
> +
yep, changed

2018-11-01 14:39 UTC, nsaenz7 commented on lib/setupCustomRoutes.js
> +            return routers.routerSetup.call(null, router);
yep, added iterator to go through all exported functions not just the one

2018-11-01 14:45 UTC, sshankar19 approved these changes

2018-11-01 14:46 UTC, sshankar19 approved these changes

2018-11-02 15:30 UTC, nikmash commented on lib/setupCustomRoutes.js
> +    const routerFilePath = appDirectory + '/apps/' + mainAppName + '/server/routes/index.js';
Can we pass in the file path instead? So it gives more control to the consumer?

2018-11-02 15:51 UTC, nsaenz7 commented on lib/setupCustomRoutes.js
> +    const routerFilePath = appDirectory + '/apps/' + mainAppName + '/server/routes/index.js';
we could, I don't know if there's a perfect solution, it just depends how opinionated we want our framework to be about how the user organizes things. the thinking was the user should probably organize things in a similar way anyway, so it might be helpful to define some structure. if we didn't do it this way, the custom file path would be yet another thing we have to pass into the listen function, and I didn't think it'd be too burdensome to the user to put this file in a specific place since we ask them to do that already with others. but if there's a good reason the consumer would need this control then I'll add that!

2018-11-05 15:31 UTC, sshankar19 commented on lib/setupCustomRoutes.js
> +    const routerFilePath = appDirectory + '/apps/' + mainAppName + '/server/routes/index.js';
We already have convention in the framework with the controller, apps/common/js/ etc., I don't think it makes sense to do half-config/half-convention here.  The more we force convention also, the more clearly defined pattern there is for people to replicate. AND there's less variables/moving parts to debug. As a framework we will _always know that it should be in that path_

2018-11-05 15:52 UTC, nikmash approved these changes

2018-11-05 15:53 UTC, merged