Inject a method to expose session object.
haven-life/amorphic-server pull request #3
Opened 2018-05-18 17:57 UTC by srksag

2018-05-18 21:00 UTC, sshankar19 requested changes

2018-05-18 21:00 UTC, sshankar19 commented on lib/session/establishContinuedServerSession.js
> +                    return amorphicSession;
instead of doing it this way, can you add a getter and setter in supertype or in amorphic on the template? That way we don't have to tie the scoping of getAmorphicSession to the var here.

2018-05-21 16:52 UTC, nikmash commented
`package-lock.json` needs to be updated

2018-05-22 13:19 UTC, srksag commented
Closing this as I found an issue with this fix

2018-05-22 13:19 UTC, closed without merging