Swat/feature/merging master into daemon mode
haven-life/amorphic-server pull request #34
Opened 2018-12-13 21:16 UTC by sshankar19

2018-12-13 21:18 UTC, nikmash submitted a review, later dismissed

2018-12-17 16:49 UTC, nsaenz7 approved these changes

2018-12-17 16:58 UTC, nsaenz7 approved these changes

2018-12-17 17:09 UTC, hackerrdave requested changes

2018-12-17 17:09 UTC, hackerrdave commented on HISTORY.md
> +* Updating supertype to 3.1.0, adding a public api to allow customization of supertype's logging functionality
updating supertype to 3.1.0 is occurring in Amorphic v4.0.0 not Amorphic v3.1.0 correct?

2018-12-17 18:19 UTC, sshankar19 commented on HISTORY.md
> +* Updating supertype to 3.1.0, adding a public api to allow customization of supertype's logging functionality
No, this happened already in Amorphic 3.1, and that was already published. I'm just porting those changes back into Amorphic 4.0

2018-12-17 18:22 UTC, nikmash commented on HISTORY.md
> +* Updating supertype to 3.1.0, adding a public api to allow customization of supertype's logging functionality
Hilariously confusing because it's both amorphic 3.1.0 and supertype 3.1.0

2018-12-17 18:26 UTC, hackerrdave commented on HISTORY.md
> +* Updating supertype to 3.1.0, adding a public api to allow customization of supertype's logging functionality
what's the merging strategy for the various branches/versions?

2018-12-17 18:26 UTC, hackerrdave commented on HISTORY.md
> +* Updating supertype to 3.1.0, adding a public api to allow customization of supertype's logging functionality
hard to know how to review this PR w/o understanding our branching/versioning

2018-12-17 20:22 UTC, sshankar19 commented on HISTORY.md
> +* Updating supertype to 3.1.0, adding a public api to allow customization of supertype's logging functionality
After this MR, we will merge this branch into master, and then publish 4.0. Thought about maintaining two different versions of amorphic and that's too much work.

2018-12-17 20:30 UTC, hackerrdave approved these changes

2018-12-17 22:15 UTC, merged