Retry client POSTs on status code 0
haven-life/amorphic-server pull request #37
Opened 2019-03-07 17:36 UTC by bealeofsteel

The amorphic client currently receives a status code of 0 when the internet connection is lost, but it handles these responses the same way it handles 200s.  It should instead retry those requests (as it does with 503 responses) so that front-end changes can be persisted when the connection is restored.

2019-03-14 21:08 UTC, hackerrdave requested changes

2019-03-14 21:08 UTC, hackerrdave commented on client.js
> +            if (status == 200) {
can we do a strict comparison here? status is always a number correct?

2019-03-14 21:08 UTC, hackerrdave commented on client.js
> +                if ((status == 500 || status == 502 || status == 503 || status == 504 || status == 0) && --retries) {
same here - can do strict comparisons?

2019-03-14 22:02 UTC, bealeofsteel commented on client.js
> +                if ((status == 500 || status == 502 || status == 503 || status == 504 || status == 0) && --retries) {
done

2019-03-14 22:02 UTC, bealeofsteel commented on client.js
> +            if (status == 200) {
done

2019-03-18 14:50 UTC, hackerrdave commented on client.js
> +                if ((status === 500 || status === 502 || status === 503 || status === 504 || status === 0) && --retries) {
nit: may be worth extracting this into a separate function called `isErrorStatus()`, for example:

```javascript
function isErrorStatus(status) {
  const errorStatuses = new Set([500, 502, 503, 504, 0]);

  return errorStatuses.has(status);
}

if (isErrorStatus(status) && --retries) {
```

2019-03-18 15:12 UTC, bealeofsteel commented on client.js
> +                if ((status === 500 || status === 502 || status === 503 || status === 504 || status === 0) && --retries) {
Done

2019-03-18 17:27 UTC, nsaenz7 submitted a review, later dismissed

2019-03-18 19:30 UTC, hackerrdave submitted a review, later dismissed

2019-03-26 21:25 UTC, nikmash submitted a review, later dismissed

2019-03-27 17:17 UTC, basdag commented on client.js
> -            if (status == 200 || status == 0) {
I believe we will need to update the HISTORY.md and package files as well with a newer version. In this case since it is a fix it should be `4.2.1`.

2019-03-27 17:27 UTC, nsaenz7 approved these changes

2019-03-28 18:08 UTC, nikmash approved these changes

2019-03-29 19:40 UTC, merged