Add hook to insert statsd client to measure amorphic internal stats
haven-life/amorphic-server pull request #44
Opened 2019-05-15 19:49 UTC by nsaenz7

things that were changed:
- add a statsd client and place it onto supertype for use by other amorphic subcomponents
- implement timing functions in important areas of amorphic codebase

things that didn't change:
- testing infrastructure is not good. going to fix with more 'real world' updated typescript tests in a separate ticket.

2019-05-15 20:01 UTC, sshankar19 approved these changes

2019-05-15 20:01 UTC, sshankar19 commented on tsconfig.json
>      "./lib/AmorphicServer.ts"
why'd you change this?

2019-05-16 14:13 UTC, sshankar19 requested changes

2019-05-16 14:13 UTC, sshankar19 commented on lib/routes/processMessage.js
>                  res.end(respstr);
whitespace?

2019-05-16 14:13 UTC, sshankar19 commented on lib/routes/processMessage.js
> +            // log(0, req.session.id, error.message + error.stack, nonObjTemplatelogLevel);
do we not want this log thing?

2019-05-16 14:13 UTC, sshankar19 commented on lib/session/compressSessionData.js
> +                { result: 'success' });
result: 'success'?

2019-05-16 14:55 UTC, nsaenz7 commented on tsconfig.json
>      "./lib/AmorphicServer.ts"
not a super significant change, they do different flavors of the same thing. `include` is used when you're using some sort of pattern matching, but we're explicitly saying "I want this file and only this file", so I used the tsconfig prop that seemed to best match that behavior, `files`.

2019-05-16 14:55 UTC, nsaenz7 commented on lib/routes/processMessage.js
> +            // log(0, req.session.id, error.message + error.stack, nonObjTemplatelogLevel);
nope! we do. will uncomment

2019-05-16 14:55 UTC, nsaenz7 commented on lib/session/compressSessionData.js
> +                { result: 'success' });
darn, will change to `failure`. good catch!

2019-05-16 15:00 UTC, nsaenz7 commented on lib/routes/processMessage.js
>                  res.end(respstr);
this was intentional, I just wanted to see some more space here haha

2019-05-17 15:06 UTC, sshankar19 submitted a review, later dismissed

2019-06-03 15:19 UTC, sshankar19 approved these changes

2019-06-03 17:05 UTC, nikmash approved these changes

2019-06-03 17:24 UTC, merged