HL-16388 => Improve Auto Logout Time Accuracy
haven-life/amorphic-server pull request #48
Opened 2019-06-05 19:05 UTC by nsaenz7

Refactor the auto logout timer to be more accurate.

Auto logout time at a maximum
_before_: (session expiration seconds * 2)
_after_: (session expiration seconds + session heartbeat seconds)

**example:** if intended auto logout time is 30 minutes, with an activity heartbeat of 20 seconds..
_before_: auto logout could happen anywhere between 30 minutes and 60 minutes.
_after_: auto logout could happen anywhere between 30 minutes and 30 minutes 20 seconds.

Secondary changes: add comments, use most applicable controller function to trigger client coded logout functionality.

2019-06-05 19:14 UTC, sshankar19 requested changes

2019-06-05 19:14 UTC, sshankar19 commented on client.js
> +    activityHeartbeatInterval: 20000,
Should this be configurable on the application side?

2019-06-05 19:14 UTC, sshankar19 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
Should we make this explicit in the log statement that we're calling the custom expire from the controller?

2019-06-05 20:33 UTC, nsaenz7 commented on client.js
> +    activityHeartbeatInterval: 20000,
Yes it should be, but I'm thinking we do this in a separate ticket since this MR is just putting out the fire - we can make it easier and nicer to use in a separate ticket. this change would add a decent amount of scope to this MR (reading config from apps, testing to make sure defaults work, etc.). I'll put a ticket in framework backlog to make this configurable

2019-06-05 20:34 UTC, nsaenz7 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
Agreed, these old comments are redundant...after speaking with @nikmash he was thinking we should actually try and obfuscate session expiration related logs, especially if they're just on the client. in this example, deleting these logs altogether. thoughts? @sshankar19

2019-06-05 20:37 UTC, sshankar19 commented on client.js
> +    activityHeartbeatInterval: 20000,
Considering that we don't really need that ASAP (Like immediately, and rather by the end of the month), I strongly believe we should add this into the scope of this MR. If you think that it's more than a few days of work, then maybe. But I don't know considering this part is already tested.

2019-06-05 20:40 UTC, sshankar19 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
Well we can just move these to debug level logs if that's possible? That way from the developer's perspective it makes it a bit clear

Also I was thinking more along the lines of being more explicit like
`console.log('Server session ready to expire, controller resetting itself to be offline using defined functionality');`

2019-06-05 20:47 UTC, sshankar19 commented on client.js
> +    activityHeartbeatInterval: 20000,
The counter point is, this work will keep getting pushed off. If we're going to make this feature, I'd rather we do it right from the start

2019-06-05 20:52 UTC, nsaenz7 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
thinking about it more, I'd encourage a dev consuming this app to instead add their own logs. e.g. if you wanted a log saying you used your specific logout function, include those logs yourself in that function. that way you'd have the choice of exposing that log on the client, server, or not at all. so I'm going to just remove the log statement from the custom functionality block. the `else` log would remain as is.

2019-06-05 21:18 UTC, nsaenz7 commented on client.js
> +    activityHeartbeatInterval: 20000,
I think the current state accomplishes what the ticket requires (better auto log out time granularity), in a way that doesn't block future improvement (making more configurable with per-app heartbeat time config). so I don't see a huge reason to not merge this in with the intent of adding flexible config later - especially given we have a lot of other priorities to juggle. We can deliver a working fix, and give ourselves enough time to get other stuff done first before we come back to improving this solution. Plus this way, we can merge down at the beginning of this sprint to hammer out any issues in the base functionality, which is the most important part of this MR.

2019-06-05 21:22 UTC, nsaenz7 commented on client.js
> +    activityHeartbeatInterval: 20000,
if you still feel strongly this should not get merged without config driven heartbeat time, I respect that and I will table this MR for later. if you're OK with merging this (after testing of course) to get something working, that's cool too just resolve the comment thread

2019-06-06 14:43 UTC, sshankar19 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
Hmm, i'm fine if you remove it, just edit the comment above 
`// check to see if the consuming app has defined logout functionality`
to just also say
`// check to see if the consuming app has defined logout functionality and call it`

2019-06-06 14:44 UTC, sshankar19 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
Since client.js is the file that most consumers are most concerned about, I'd like it to be as easy to parse and understand as possible. Maybe it's nitpicky, even if you don't edit that comment it should be okay.

2019-06-13 14:00 UTC, nsaenz7 commented on client.js
> +    activityHeartbeatInterval: 20000,
https://massmutual.atlassian.net/browse/HL-16841

2019-06-13 14:01 UTC, nsaenz7 commented on client.js
> +                console.log('Server session ready to expire, controller resetting itself to be offline');
ok, removed console log from customer function, and updated comment

2019-06-13 18:56 UTC, nikmash submitted a review, later dismissed

2019-06-13 20:22 UTC, sshankar19 approved these changes

2019-06-13 20:24 UTC, nikmash approved these changes
3rd time is the charm

2019-06-13 20:25 UTC, merged